name: sturdy_http
description: A strongly typed, event-based, reliable HTTP client that wraps `Dio`.
version: 0.6.1
homepage: https://github.com/Betterment/sturdy_http
repository: https://github.com/Betterment/sturdy_http

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  collection: ^1.19.1
  dio: ^5.9.0
  uuid: ^4.5.2

dev_dependencies:
  charlatan: ^0.5.0
  lints: ^5.1.1
  test: ^1.29.0
