name: sturdy_http
description: A strongly typed, event-based, reliable HTTP client that wraps `Dio`.
version: 0.5.1
homepage: https://github.com/Betterment/sturdy_http
repository: https://github.com/Betterment/sturdy_http

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dio: ^5.7.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.12
  charlatan: ^0.4.0
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.8
