name: sturdy_http
description: A strongly typed, event-based, reliable HTTP client that wraps `Dio`.
version: 0.6.0
homepage: https://github.com/Betterment/sturdy_http
repository: https://github.com/Betterment/sturdy_http

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.4
  charlatan: ^0.5.0
  lints: ^6.0.0
  test: ^1.28.0
